### PR TITLE
Use `generic_url` instead `image_url_thumbnail`

### PR DESCRIPTION
**Pull request by sgruetter**
The new URL _should_ work on production as `generic_url` is deployed everywhere. However, I don't know how to test this locally, thus I'd rather do this together.

### CODE REVIEW

**Comment by thisguyscode** [comment]
@sgruetter Do you still need a response here?

**Comment by sgruetter** [comment]
Yes - we will remove the replaced URL at some point, so it would be good to get this change out.

**Comment by thisguyscode** [comment]
Let's give @jonasbuechel a little bump then. I don't know what this is about exactly. Alternatively can assign @charlietango as a reviewer as he's becoming more familiar with the Sketch plugin.

**Comment by thisguyscode** [comment]
On second thought - I should be able to test this myself.

**Comment by thisguyscode** [comment]
@sgruetter - Sketch crashes at startup while this plugin is 'installed' (built and referenced). Maybe solved by merging the new master in, but on first glance doesn't seem stable in its current form.

**Comment by sgruetter** [comment]
@thisguyscode Thanks for the feedback. I rebased on master. Can you try again?

**Comment by thisguyscode** [comment]
Seems fine to me. Didn't test video because my image-worker is not working. Any reason video wouldn't work, or shall we merge?

Screenshot 2020-05-05 at 11 59 51
Screenshot 2020-05-05 at 11 59 53
Screenshot 2020-05-05 at 11 59 55

**Comment by sgruetter** [comment]
Thanks for testing @thisguyscode. Videos should work, too, as the URL is used for previews (with the width added). If you approve, I'll merge (or you can also merge if you approve).

**Pull request merged**
